# 6. Are the paper's claims reproduced?

Every claim is checked automatically from the result tables (`src/claims.py`).
Verdicts: Yes / Partly / No.

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))  # project root, so `src` can be imported

import json
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import Image, display

from src.config import FIGURES_DIR, RESULTS_DIR

pd.set_option("display.precision", 2)

In [2]:
from src.claims import all_claims

pd.set_option("display.max_colwidth", None)

## Raw ECG (as recorded)

In [3]:
all_claims("raw")[["verdict", "claim", "ours"]]

,verdict,claim,ours
0,Yes,PLI: filter IMF1 (better than no EMD),"IMF1: 32.2 dB, no EMD: 29.1 dB (held-out tuning records)"
1,Yes,BW: filter IMF5-8 (better than no EMD),"IMF5-8: 17.4 dB, no EMD: 13.1 dB (held-out tuning records)"
2,Yes,EM: filter IMF3-8 (better than no EMD),"IMF3-8: 14.9 dB, no EMD: 12.4 dB (held-out tuning records)"
3,No,Fig. 7: LMS beats NLMS and RLS,"LMS best at 0/5 SNRin; at 10 dB: LMS 19.5, NLMS 6.9, RLS 23.9 dB"
4,Partly,BW+PLI: EMD + LMS beats LMS without EMD,better at 2/5 SNRin (-5 dB: 20.3 vs 15.5; 10 dB: 9.5 vs 12.6 dB)
5,Partly,"Fig. 8: EMD + LMS beats articles [21, 22, 28] (their reported SNRout)",better on 2/5 records at SNRin 10 dB
6,No,"Fig. 8: SNRout at 10 dB, ours (paper)","119: 24.0 (24.6), 202: 16.8 (22.6), 213: 22.1 (25.0), 217: 19.0 (29.2), 234: 15.7 (23.9); mean |difference| 5.5 dB"
7,No,Fig. 10: PEAF best on every record (SNRin 10 dB),"PEAF best on 0/13; winners {'PDAF': 13}; mean: PEAF 3.6, SEAF 4.9, PDAF 8.6, SDAF 6.7"
8,No,Fig. 11: PEAF best at every SNRin,"PEAF best at 0/6; winners by SNRin: {-5: 'SDAF', -2: 'SDAF', 0: 'SDAF', 3: 'SDAF', 6: 'PDAF', 10: 'PDAF'}"
9,Yes,Fig. 11: SNRimp falls as SNRin rises,"true for 4/4 methods (PEAF, SEAF, PDAF, SDAF)"
10,Yes,"Fig. 11: PEAF SNRimp, ours (paper)","-5 dB: 8.5 (10.2), -2 dB: 8.2 (9.5), 0 dB: 7.9 (9.4), 3 dB: 7.1 (7.0), 6 dB: 6.0 (5.6), 10 dB: 3.6 (4.3); mean |difference| 1.0 dB"

## Normalized ECG

In [4]:
all_claims("norm")[["verdict", "claim", "ours"]]

,verdict,claim,ours
0,Yes,PLI: filter IMF1 (better than no EMD),"IMF1: 29.9 dB, no EMD: 28.6 dB (held-out tuning records)"
1,No,BW: filter IMF5-8 (better than no EMD),"IMF5-8: 14.0 dB, no EMD: 14.2 dB (held-out tuning records)"
2,No,EM: filter IMF3-8 (better than no EMD),"IMF3-8: 13.0 dB, no EMD: 13.1 dB (held-out tuning records)"
3,No,Fig. 7: LMS beats NLMS and RLS,"LMS best at 0/5 SNRin; at 10 dB: LMS 21.5, NLMS 4.9, RLS 22.5 dB"
4,Partly,BW+PLI: EMD + LMS beats LMS without EMD,better at 4/5 SNRin (-5 dB: 18.5 vs 18.5; 10 dB: 11.5 vs 11.0 dB)
5,Partly,"Fig. 8: EMD + LMS beats articles [21, 22, 28] (their reported SNRout)",better on 2/5 records at SNRin 10 dB
6,Partly,"Fig. 8: SNRout at 10 dB, ours (paper)","119: 24.1 (24.6), 202: 19.7 (22.6), 213: 24.7 (25.0), 217: 20.7 (29.2), 234: 18.3 (23.9); mean |difference| 3.6 dB"
7,No,Fig. 10: PEAF best on every record (SNRin 10 dB),"PEAF best on 0/13; winners {'PDAF': 13}; mean: PEAF 3.8, SEAF 4.3, PDAF 7.9, SDAF 3.9"
8,No,Fig. 11: PEAF best at every SNRin,"PEAF best at 0/6; winners by SNRin: {-5: 'PDAF', -2: 'PDAF', 0: 'PDAF', 3: 'PDAF', 6: 'PDAF', 10: 'PDAF'}"
9,Yes,Fig. 11: SNRimp falls as SNRin rises,"true for 4/4 methods (PEAF, SEAF, PDAF, SDAF)"
10,Yes,"Fig. 11: PEAF SNRimp, ours (paper)","-5 dB: 11.2 (10.2), -2 dB: 10.5 (9.5), 0 dB: 9.8 (9.4), 3 dB: 8.5 (7.0), 6 dB: 6.7 (5.6), 10 dB: 3.8 (4.3); mean |difference| 0.9 dB"